//
//  DesignDocGenerator.swift
//  DocKit
//
//  Generates design.md documents for projects
//

import Foundation

/// Generates design documents with decisions, constraints, and rationale
public struct DesignDocGenerator {
    
    public struct DesignInput: Sendable {
        public let projectName: String
        public let objective: String
        public let constraints: [String]
        public let decisions: [Decision]
        public let alternatives: [Alternative]
        public let diagrams: [String]
        public let reviewers: [String]
        
        public init(
            projectName: String,
            objective: String,
            constraints: [String] = [],
            decisions: [Decision] = [],
            alternatives: [Alternative] = [],
            diagrams: [String] = [],
            reviewers: [String] = []
        ) {
            self.projectName = projectName
            self.objective = objective
            self.constraints = constraints
            self.decisions = decisions
            self.alternatives = alternatives
            self.diagrams = diagrams
            self.reviewers = reviewers
        }
    }
    
    public struct Decision: Sendable {
        public let title: String
        public let description: String
        public let rationale: String
        public let status: String
        
        public init(title: String, description: String, rationale: String, status: String = "Accepted") {
            self.title = title
            self.description = description
            self.rationale = rationale
            self.status = status
        }
    }
    
    public struct Alternative: Sendable {
        public let title: String
        public let description: String
        public let pros: [String]
        public let cons: [String]
        public let rejected: Bool
        
        public init(title: String, description: String, pros: [String], cons: [String], rejected: Bool = true) {
            self.title = title
            self.description = description
            self.pros = pros
            self.cons = cons
            self.rejected = rejected
        }
    }
    
    public static func generate(from input: DesignInput) -> String {
        var md = """
        # Design Document: \(input.projectName)
        
        > Generated by DocKit on \(formattedDate())
        
        ## Objective
        
        \(input.objective)
        
        """
        
        // Constraints
        if !input.constraints.isEmpty {
            md += "## Constraints\n\n"
            for constraint in input.constraints {
                md += "- \(constraint)\n"
            }
            md += "\n"
        }
        
        // Decisions
        if !input.decisions.isEmpty {
            md += "## Design Decisions\n\n"
            for (index, decision) in input.decisions.enumerated() {
                md += """
                ### Decision \(index + 1): \(decision.title)
                
                **Status:** \(decision.status)
                
                \(decision.description)
                
                **Rationale:** \(decision.rationale)
                
                """
            }
        }
        
        // Alternatives
        if !input.alternatives.isEmpty {
            md += "## Alternatives Considered\n\n"
            for alt in input.alternatives {
                md += """
                ### \(alt.title) \(alt.rejected ? "(Rejected)" : "(Selected)")
                
                \(alt.description)
                
                **Pros:**
                \(alt.pros.map { "- \($0)" }.joined(separator: "\n"))
                
                **Cons:**
                \(alt.cons.map { "- \($0)" }.joined(separator: "\n"))
                
                """
            }
        }
        
        // Diagrams
        if !input.diagrams.isEmpty {
            md += "## Diagrams\n\n"
            for diagram in input.diagrams {
                md += "- \(diagram)\n"
            }
            md += "\n"
        }
        
        // Reviewers
        if !input.reviewers.isEmpty {
            md += "## Reviewers\n\n"
            for reviewer in input.reviewers {
                md += "- [ ] \(reviewer)\n"
            }
            md += "\n"
        }
        
        md += """
        ---
        
        ## Revision History
        
        | Version | Date | Author | Changes |
        |---------|------|--------|---------|
        | 1.0 | \(formattedDate()) | DocKit | Initial design document |
        """
        
        return md
    }
    
    private static func formattedDate() -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter.string(from: Date())
    }
}
