//
//  RequirementsGenerator.swift
//  DocKit
//
//  Generates requirements.md documents for projects
//

import Foundation

/// Generates requirements documents
public struct RequirementsGenerator {
    
    public struct RequirementsInput: Sendable {
        public let projectName: String
        public let version: String
        public let functionalRequirements: [Requirement]
        public let nonFunctionalRequirements: [Requirement]
        public let constraints: [String]
        public let assumptions: [String]
        public let dependencies: [String]
        public let owner: String
        
        public init(
            projectName: String,
            version: String = "1.0",
            functionalRequirements: [Requirement] = [],
            nonFunctionalRequirements: [Requirement] = [],
            constraints: [String] = [],
            assumptions: [String] = [],
            dependencies: [String] = [],
            owner: String = ""
        ) {
            self.projectName = projectName
            self.version = version
            self.functionalRequirements = functionalRequirements
            self.nonFunctionalRequirements = nonFunctionalRequirements
            self.constraints = constraints
            self.assumptions = assumptions
            self.dependencies = dependencies
            self.owner = owner
        }
    }
    
    public struct Requirement: Sendable {
        public let id: String
        public let title: String
        public let description: String
        public let priority: Priority
        public let status: Status
        public let acceptanceCriteria: [String]
        
        public init(
            id: String,
            title: String,
            description: String,
            priority: Priority = .should,
            status: Status = .proposed,
            acceptanceCriteria: [String] = []
        ) {
            self.id = id
            self.title = title
            self.description = description
            self.priority = priority
            self.status = status
            self.acceptanceCriteria = acceptanceCriteria
        }
        
        public enum Priority: String, Sendable {
            case must = "Must Have"
            case should = "Should Have"
            case could = "Could Have"
            case wont = "Won't Have"
        }
        
        public enum Status: String, Sendable {
            case proposed = "Proposed"
            case approved = "Approved"
            case implemented = "Implemented"
            case verified = "Verified"
            case deferred = "Deferred"
        }
    }
    
    public static func generate(from input: RequirementsInput) -> String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"
        
        var md = """
        # Requirements: \(input.projectName)
        
        > Version \(input.version) | Generated by DocKit on \(dateFormatter.string(from: Date()))
        
        """
        
        if !input.owner.isEmpty {
            md += "**Owner:** \(input.owner)\n\n"
        }
        
        // Summary
        md += """
        ## Summary
        
        | Category | Count |
        |----------|-------|
        | Functional Requirements | \(input.functionalRequirements.count) |
        | Non-Functional Requirements | \(input.nonFunctionalRequirements.count) |
        | Constraints | \(input.constraints.count) |
        | Dependencies | \(input.dependencies.count) |
        
        ---
        
        """
        
        // Functional Requirements
        if !input.functionalRequirements.isEmpty {
            md += "## Functional Requirements\n\n"
            md += generateRequirementsTable(input.functionalRequirements)
            md += "\n"
            
            for req in input.functionalRequirements {
                md += generateRequirementDetail(req)
            }
        }
        
        // Non-Functional Requirements
        if !input.nonFunctionalRequirements.isEmpty {
            md += "## Non-Functional Requirements\n\n"
            md += generateRequirementsTable(input.nonFunctionalRequirements)
            md += "\n"
            
            for req in input.nonFunctionalRequirements {
                md += generateRequirementDetail(req)
            }
        }
        
        // Constraints
        if !input.constraints.isEmpty {
            md += "## Constraints\n\n"
            for constraint in input.constraints {
                md += "- \(constraint)\n"
            }
            md += "\n"
        }
        
        // Assumptions
        if !input.assumptions.isEmpty {
            md += "## Assumptions\n\n"
            for assumption in input.assumptions {
                md += "- \(assumption)\n"
            }
            md += "\n"
        }
        
        // Dependencies
        if !input.dependencies.isEmpty {
            md += "## Dependencies\n\n"
            for dep in input.dependencies {
                md += "- \(dep)\n"
            }
            md += "\n"
        }
        
        md += """
        ---
        
        ## Revision History
        
        | Version | Date | Author | Changes |
        |---------|------|--------|---------|
        | \(input.version) | \(dateFormatter.string(from: Date())) | DocKit | Initial requirements |
        """
        
        return md
    }
    
    private static func generateRequirementsTable(_ requirements: [Requirement]) -> String {
        var table = "| ID | Title | Priority | Status |\n"
        table += "|-----|-------|----------|--------|\n"
        
        for req in requirements {
            table += "| \(req.id) | \(req.title) | \(req.priority.rawValue) | \(req.status.rawValue) |\n"
        }
        
        return table
    }
    
    private static func generateRequirementDetail(_ req: Requirement) -> String {
        var detail = """
        ### \(req.id): \(req.title)
        
        **Priority:** \(req.priority.rawValue) | **Status:** \(req.status.rawValue)
        
        \(req.description)
        
        """
        
        if !req.acceptanceCriteria.isEmpty {
            detail += "**Acceptance Criteria:**\n"
            for (index, criteria) in req.acceptanceCriteria.enumerated() {
                detail += "\(index + 1). \(criteria)\n"
            }
            detail += "\n"
        }
        
        return detail
    }
}
