//
//  SpecsGenerator.swift
//  DocKit
//
//  Generates specs.md documents for projects
//

import Foundation

/// Generates specification documents
public struct SpecsGenerator {
    
    public struct SpecsInput: Sendable {
        public let projectName: String
        public let version: String
        public let overview: String
        public let features: [FeatureSpec]
        public let apis: [APISpec]
        public let dataModels: [DataModelSpec]
        public let integrations: [IntegrationSpec]
        
        public init(
            projectName: String,
            version: String = "1.0",
            overview: String = "",
            features: [FeatureSpec] = [],
            apis: [APISpec] = [],
            dataModels: [DataModelSpec] = [],
            integrations: [IntegrationSpec] = []
        ) {
            self.projectName = projectName
            self.version = version
            self.overview = overview
            self.features = features
            self.apis = apis
            self.dataModels = dataModels
            self.integrations = integrations
        }
    }
    
    public struct FeatureSpec: Sendable {
        public let name: String
        public let description: String
        public let userStories: [String]
        public let technicalNotes: String
        
        public init(name: String, description: String, userStories: [String] = [], technicalNotes: String = "") {
            self.name = name
            self.description = description
            self.userStories = userStories
            self.technicalNotes = technicalNotes
        }
    }
    
    public struct APISpec: Sendable {
        public let name: String
        public let method: String
        public let endpoint: String
        public let description: String
        public let parameters: [Parameter]
        public let response: String
        
        public init(name: String, method: String, endpoint: String, description: String, parameters: [Parameter] = [], response: String = "") {
            self.name = name
            self.method = method
            self.endpoint = endpoint
            self.description = description
            self.parameters = parameters
            self.response = response
        }
        
        public struct Parameter: Sendable {
            public let name: String
            public let type: String
            public let required: Bool
            public let description: String
            
            public init(name: String, type: String, required: Bool, description: String) {
                self.name = name
                self.type = type
                self.required = required
                self.description = description
            }
        }
    }
    
    public struct DataModelSpec: Sendable {
        public let name: String
        public let description: String
        public let properties: [Property]
        
        public init(name: String, description: String, properties: [Property] = []) {
            self.name = name
            self.description = description
            self.properties = properties
        }
        
        public struct Property: Sendable {
            public let name: String
            public let type: String
            public let description: String
            
            public init(name: String, type: String, description: String) {
                self.name = name
                self.type = type
                self.description = description
            }
        }
    }
    
    public struct IntegrationSpec: Sendable {
        public let name: String
        public let type: String
        public let description: String
        public let configuration: [String: String]
        
        public init(name: String, type: String, description: String, configuration: [String: String] = [:]) {
            self.name = name
            self.type = type
            self.description = description
            self.configuration = configuration
        }
    }
    
    public static func generate(from input: SpecsInput) -> String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"
        
        var md = """
        # Specification: \(input.projectName)
        
        > Version \(input.version) | Generated by DocKit on \(dateFormatter.string(from: Date()))
        
        ## Overview
        
        \(input.overview.isEmpty ? "Technical specification for \(input.projectName)." : input.overview)
        
        """
        
        // Features
        if !input.features.isEmpty {
            md += "## Features\n\n"
            for feature in input.features {
                md += """
                ### \(feature.name)
                
                \(feature.description)
                
                """
                
                if !feature.userStories.isEmpty {
                    md += "**User Stories:**\n"
                    for story in feature.userStories {
                        md += "- \(story)\n"
                    }
                    md += "\n"
                }
                
                if !feature.technicalNotes.isEmpty {
                    md += "**Technical Notes:** \(feature.technicalNotes)\n\n"
                }
            }
        }
        
        // APIs
        if !input.apis.isEmpty {
            md += "## API Specification\n\n"
            for api in input.apis {
                md += """
                ### \(api.name)
                
                `\(api.method) \(api.endpoint)`
                
                \(api.description)
                
                """
                
                if !api.parameters.isEmpty {
                    md += "**Parameters:**\n\n"
                    md += "| Name | Type | Required | Description |\n"
                    md += "|------|------|----------|-------------|\n"
                    for param in api.parameters {
                        md += "| \(param.name) | \(param.type) | \(param.required ? "Yes" : "No") | \(param.description) |\n"
                    }
                    md += "\n"
                }
                
                if !api.response.isEmpty {
                    md += "**Response:**\n```json\n\(api.response)\n```\n\n"
                }
            }
        }
        
        // Data Models
        if !input.dataModels.isEmpty {
            md += "## Data Models\n\n"
            for model in input.dataModels {
                md += """
                ### \(model.name)
                
                \(model.description)
                
                """
                
                if !model.properties.isEmpty {
                    md += "| Property | Type | Description |\n"
                    md += "|----------|------|-------------|\n"
                    for prop in model.properties {
                        md += "| \(prop.name) | \(prop.type) | \(prop.description) |\n"
                    }
                    md += "\n"
                }
            }
        }
        
        // Integrations
        if !input.integrations.isEmpty {
            md += "## Integrations\n\n"
            for integration in input.integrations {
                md += """
                ### \(integration.name)
                
                **Type:** \(integration.type)
                
                \(integration.description)
                
                """
                
                if !integration.configuration.isEmpty {
                    md += "**Configuration:**\n```yaml\n"
                    for (key, value) in integration.configuration.sorted(by: { $0.key < $1.key }) {
                        md += "\(key): \(value)\n"
                    }
                    md += "```\n\n"
                }
            }
        }
        
        return md
    }
}
