//
//  TasksGenerator.swift
//  DocKit
//
//  Generates tasks.md documents for projects
//

import Foundation

/// Generates task list documents
public struct TasksGenerator {
    
    public struct TasksInput: Sendable {
        public let projectName: String
        public let description: String
        public let tasks: [TaskItem]
        public let owner: String
        
        public init(projectName: String, description: String, tasks: [TaskItem] = [], owner: String = "") {
            self.projectName = projectName
            self.description = description
            self.tasks = tasks
            self.owner = owner
        }
    }
    
    public struct TaskItem: Sendable {
        public let title: String
        public let description: String
        public let status: TaskStatus
        public let priority: TaskPriority
        public let assignee: String?
        public let dueDate: Date?
        public let subtasks: [String]
        
        public init(
            title: String,
            description: String = "",
            status: TaskStatus = .todo,
            priority: TaskPriority = .medium,
            assignee: String? = nil,
            dueDate: Date? = nil,
            subtasks: [String] = []
        ) {
            self.title = title
            self.description = description
            self.status = status
            self.priority = priority
            self.assignee = assignee
            self.dueDate = dueDate
            self.subtasks = subtasks
        }
    }
    
    public enum TaskStatus: String, Sendable {
        case todo = "To Do"
        case inProgress = "In Progress"
        case review = "In Review"
        case done = "Done"
        case blocked = "Blocked"
        
        public var emoji: String {
            switch self {
            case .todo: return "⬜"
            case .inProgress: return "🔄"
            case .review: return "👀"
            case .done: return "✅"
            case .blocked: return "🚫"
            }
        }
    }
    
    public enum TaskPriority: String, Sendable {
        case critical = "Critical"
        case high = "High"
        case medium = "Medium"
        case low = "Low"
        
        public var emoji: String {
            switch self {
            case .critical: return "🔴"
            case .high: return "🟠"
            case .medium: return "🟡"
            case .low: return "🟢"
            }
        }
    }
    
    public static func generate(from input: TasksInput) -> String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"
        
        var md = """
        # Tasks: \(input.projectName)
        
        > Generated by DocKit on \(dateFormatter.string(from: Date()))
        
        \(input.description)
        
        """
        
        if !input.owner.isEmpty {
            md += "**Owner:** \(input.owner)\n\n"
        }
        
        // Summary
        let todoCount = input.tasks.filter { $0.status == .todo }.count
        let inProgressCount = input.tasks.filter { $0.status == .inProgress }.count
        let doneCount = input.tasks.filter { $0.status == .done }.count
        
        md += """
        ## Summary
        
        | Status | Count |
        |--------|-------|
        | ⬜ To Do | \(todoCount) |
        | 🔄 In Progress | \(inProgressCount) |
        | ✅ Done | \(doneCount) |
        | **Total** | **\(input.tasks.count)** |
        
        ---
        
        ## Task List
        
        """
        
        // Group by status
        let grouped = Dictionary(grouping: input.tasks) { $0.status }
        let statusOrder: [TaskStatus] = [.inProgress, .todo, .review, .blocked, .done]
        
        for status in statusOrder {
            guard let tasks = grouped[status], !tasks.isEmpty else { continue }
            
            md += "### \(status.emoji) \(status.rawValue)\n\n"
            
            for task in tasks {
                let checkbox = status == .done ? "[x]" : "[ ]"
                let priorityBadge = task.priority.emoji
                
                md += "- \(checkbox) \(priorityBadge) **\(task.title)**"
                
                if let assignee = task.assignee {
                    md += " (@\(assignee))"
                }
                
                if let due = task.dueDate {
                    md += " - Due: \(dateFormatter.string(from: due))"
                }
                
                md += "\n"
                
                if !task.description.isEmpty {
                    md += "  - \(task.description)\n"
                }
                
                for subtask in task.subtasks {
                    md += "  - [ ] \(subtask)\n"
                }
            }
            
            md += "\n"
        }
        
        md += """
        ---
        
        ## Legend
        
        **Priority:** 🔴 Critical | 🟠 High | 🟡 Medium | 🟢 Low
        
        **Status:** ⬜ To Do | 🔄 In Progress | 👀 Review | ✅ Done | 🚫 Blocked
        """
        
        return md
    }
}
