//
//  DocsPackage.swift
//  IdeaKit - Project Operating System
//
//  Kernel Package: Documentation
//  Central documentation brain - cross-links, indexes, health checks
//  Produces: Documentation index, health reports
//

import Foundation

/// Documentation Package
/// Central documentation intelligence
public struct DocsPackage: CapabilityPackage {
    
    public static let packageId = "docs"
    public static let name = "Documentation Package"
    public static let description = "Central documentation brain that cross-links specs, tasks, and code"
    public static let version = "1.0.0"
    public static let produces = ["DocsIndex"]
    public static let consumes = ["*"]  // Consumes all artifacts
    public static let isKernel = true
    
    public init() {}
    
    public func execute(graph: ArtifactGraph, context: ProjectContext) async throws {
        // Generate documentation index
        let index = await generateIndex(graph: graph, context: context)
        try context.save(artifact: index, as: "docs_index.md")
        
        // Generate artifact graph visualization
        let graphMd = await graph.toMarkdown()
        try context.save(artifact: graphMd, as: "artifact_graph.md")
    }
    
    private func generateIndex(graph: ArtifactGraph, context: ProjectContext) async -> String {
        let artifactIds = await graph.allArtifactIds()
        
        var md = "# Documentation Index\n\n"
        md += "_Auto-generated by DocsPackage_\n\n"
        
        md += "## Artifacts (\(artifactIds.count))\n\n"
        md += "| Artifact | Type | Producer |\n"
        md += "|----------|------|----------|\n"
        
        for id in artifactIds {
            if let metadata = await graph.metadata(for: id) {
                md += "| \(id) | \(metadata.type) | \(metadata.producedBy) |\n"
            }
        }
        
        md += "\n## Documents\n\n"
        md += "- [Intent](intent.md)\n"
        md += "- [Assumptions](assumptions.md)\n"
        md += "- [Requirements](requirements.md)\n"
        md += "- [Scope](scope.md)\n"
        md += "- [Architecture](architecture.md)\n"
        md += "- [Tasks](tasks.md)\n"
        md += "- [Risks](risks.md)\n"
        
        return md
    }
}
